[build]
    command = "npm run build"
    publish = "dist"
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
[[headers]]
    for = "/*"
        [headers.values]
            Cache-Control = "max-age=31536000"
            X-Content-Type-Options = "DENY"
            Content-Security-Policy = "default-src 'self' 'unsafe-inline' *.cloudfront.net; style-src 'unsafe-inline'; style-src-elem 'unsafe-inline' *.cloudfront.net web-accessibility-hotequil.netlify.app; font-src fonts.gstatic.com"
            X-Frame-Options = "SAMEORIGIN"
            X-XSS-Protection = "1; mode=block"
